### PR TITLE
An initial draft of the R Styleguide

### LINKED ISSUE #1: Create initial version of R Styleguide
This will be a markdown file based on @beperron's "CADL Coding Conventions" file hosted on Slack, [Google's styleguide](https://google-styleguide.googlecode.com/svn/trunk/Rguide.xml), and [Hadley's styleguide](http://adv-r.had.co.nz/Style.html).

### PR DESCRIPTION
**Pull request by ClaytonJY**
This is a modified version of the styleguide I wrote and maintain for my day job. It strives to specify all relevant guidelines, rather than only listing deviations from a different styleguide. It includes a lot of stuff from Hadley in addition to Google's styleguide.

Pretty much everything here is up for discussion, and I expect changes will need to be made.

Some of the more controversial guidelines:
- no periods in variable names; I feel strongly about this, as do modern package writers. Periods are bad, mmkay?
- put function doc comments _before_ the function; feels more consistent with documenting package functions with Roxygen2, I think it looks awkward inside the function
- specify types/classes of arguments in function doc comments; an extension of the Google standard that can be either helpful or pedantic

Other notes:
- file names: I don't care much what the naming convention is, this is just what we settled on at Barracuda
- `data.table` examples: I removed most of them, but there's still examples in the `Organization` section which refer to data.table concepts; should these be replaced?

@beperron, @bryanvictor, @hereismyname, please review. I suggest using the "view rich diff" button to see the rendered html rather than reviewing markdown source.

Closes #1.

### CODE REVIEW

**Comment by hereismyname** [comment]
Check line 121-- this appears redundant and also against what you're advising:
```
x <- foobar(a = "foo", b = "bar")
x <- foobar(a="foo", b="bar")
```

How does everyone feel about adopting Clayton's conventions for function names?
E.g. `plot_height(x)` versus `plotHeight(x)`?

**Comment by beperron** [comment]
I'm in agreement with the style guide.  I have been advising to use camelCase for variable name specification and use that in nearly all my work.  But, that is more out of habit, and I would prefer to get closer to best practices used in the coding community.  We can submit an issue later on to work on code clean-up to conform to this policy.

**Comment by ClaytonJY** [comment]
@beperron that reminds me, I should add something about column names for clean/unclean variables. I like that you guys distinguish by name, though if we move from `variableName` to `variable_name`, we might want unclean variables to go from `variableNameX` to something like `variable_name_x` or `variable_name_raw`.

I'm not too particular on any of the naming conventions, and could be convinced could to change this doc to match conventions already used. We could also have different variable naming conventions for column variables, whatever works.

**Comment by beperron** [comment]
I agree with the style guide.  I remain open to subsequent revisions, and we will continue to have discussions.  But, in my opinion, this represents an excellent set of base policies.  I approve this work but will keep this open until others have reviewed and approved.

**Comment by hereismyname** [comment]
Sussed some things out with @ClaytonJY on Slack today, feel like we're on the same page. Need to hear from @bryanvictor next.

**Comment by bryanvictor** [comment]
Looks good to me.  Happy to have a strong starting point for standardizing our work.

**Comment by ClaytonJY** [comment]
Just made all the changes as discussed on slack. @hereismyname, could you take one last look and merge this if you're satisfied?

**Comment by hereismyname** [comment]
Looks good, merging now.

**Pull request merged**
